### ISSUE TITLE
Error ID when connecting

### ISSUE THREAD

**Issue by philipphunger** [coyote1/ioBroker.repetier#9]
repetier.0 | 2021-02-02 20:33:41.863 | error | (50632) The id "10_0_0_17." is invalid. Ids are not allowed to end in "."
-- | -- | -- | --
repetier.0 | 2021-02-02 20:33:41.863 | error | at IncomingMessage.emit (events.js:326:22)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Object.onceWrapper (events.js:420:28)
repetier.0 | 2021-02-02 20:33:41.863 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1083:12)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Request.emit (events.js:314:20)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1161:10)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Request.emit (events.js:314:20)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Request.self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Request._callback (/opt/iobroker/node_modules/iobroker.repetier/main.js:356:37)
repetier.0 | 2021-02-02 20:33:41.863 | error | at Adapter.setObjectNotExists (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3298:17)
repetier.0 | 2021-02-02 20:33:41.863 | error | at validateId (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:532:23)
repetier.0 | 2021-02-02 20:33:41.863 | error | (50632) Error: The id "10_0_0_17." is invalid. Ids are not allowed to end in "."
repetier.0 | 2021-02-02 20:33:41.863 | error | (50632) unhandled promise rejection: The id "10_0_0_17." is invalid. Ids are not allowed to end in "."
repetier.0 | 2021-02-02 20:33:41.863 | error | (50632) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by skvarel** [comment]
https://github.com/coyote1/ioBroker.repetier/issues/10

**Comment by skvarel** [comment]
@philipphunger .. Coyote hat meine Änderungen am Code übernommen. Jetzt müsste es Fehlerfrei laufen.

Wichtig: .. wenn weiniger als vier Drucker angeschlossen sind, bitte irgendwelche Fantasienamen eintragen. Der Adpater benötigt (noch) zwingend vier Druckernamen.
